import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const handleOnBannerBtnClick = () => {
    alert("Hi Zoozz!");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee corners</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header_wrapper}>
          <Banner
            buttonText="Coffee Shops"
            handleOnClick={handleOnBannerBtnClick}
          />
          <div className={styles.header_image_wrapper}>
            <Image
              className={styles.header_image}
              src="/images/head_bg.png"
              width={500}
              height={500}
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
